# Generated by Django 5.0.2 on 2024-02-11 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='manager', max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(default='manager_email@email.com', max_length=254)),
            ],
        ),
    ]
