# Generated by Django 5.0.2 on 2024-02-11 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_user_consolidatedvisitors_groupinfo_groups_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groups',
            name='group_info',
        ),
        migrations.RemoveField(
            model_name='groups',
            name='influencer',
        ),
        migrations.RemoveField(
            model_name='groups',
            name='link',
        ),
        migrations.RemoveField(
            model_name='link',
            name='influencer',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='link',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='influencer',
        ),
        migrations.DeleteModel(
            name='ConsolidatedVisitors',
        ),
        migrations.DeleteModel(
            name='GroupInfo',
        ),
        migrations.DeleteModel(
            name='Groups',
        ),
        migrations.DeleteModel(
            name='Link',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='Visitor',
        ),
    ]
